### PR TITLE
Small fixes and a Note

### PR DESCRIPTION
**Pull request by mghost99**

### CODE REVIEW

**Comment by phase** [comment]
Thanks! I forgot this repo even existed!

**Comment by mghost99** [comment]
Its quite nice actually, it just needs world generation and stuff like that xD

**Comment by wgaylord** [comment]
I can take a try at world gen and maybe storage or the worlds. The hard part is actually giving the player the world and everything.

**Comment by phase** [comment]
@chibill That's just compressing the chunks and sending them in ChunkDataPackets, which I figured out when working on PhaseBot.

**Comment by wgaylord** [comment]
Okay. Yeah. I could work on translating world gen over to python. Maybe even some other stuff.

**Comment by phase** [comment]
@chibill Go for it if you want to. I recently got a Raspberry Pi 2 so we can test it out :D

**Comment by wgaylord** [comment]
I got a normal RaspberryPi B also.

**Comment by mghost99** [comment]
I don't exactly have a Raspberry Pi yet, but i plan on getting one some day xD.. I just looked around for Minecraft Servers written in Python and this is the only one that actually let me connect to it without crashing upon authentication.

**Pull request merged**
